on:
- push
- workflow_dispatch

jobs:
  pdflatex:
    runs-on: ubuntu-latest
    name: Run pdflatex
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Convert to pdf
      id: convert-to-pdf
      uses: closoco/pdflatex-action@v1.0.0
      with:
        texFile: ./jasongwartz.tex
    - name: Store pdf
      uses: actions/upload-artifact@v4
      with:
        name: jasongwartz.pdf
        path: jasongwartz.pdf
